# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

spring:
  application:
    name: ClashRoyaleChallengeHub
  profiles:
    default: dev
    group:
      dev:
        - dev

server:
  port: 8082
